# Generated by Django 5.0.1 on 2025-04-27 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResidentialComplex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("built_year", models.IntegerField(blank=True, null=True)),
                ("developer", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.ImageField(null=True, upload_to="apartments_images")),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                ("parking", models.BooleanField(default=False)),
                ("amenities", models.TextField(blank=True, null=True)),
                ("min_age", models.IntegerField(blank=True, default=18, null=True)),
                ("max_age", models.IntegerField(blank=True, default=100, null=True)),
                (
                    "musical_instruments",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("allowed", "Allowed"),
                            ("negotiable", "Negotiable"),
                            ("not_allowed", "Not Allowed"),
                        ],
                        default="negotiable",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "gender_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_preference", "No preference"),
                            ("male", "Male only"),
                            ("female", "Female only"),
                        ],
                        default="no_preference",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "pets_allowed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "tenant_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("students_only", "Students only"),
                            ("working_professionals", "Working professionals"),
                            ("anyone", "Anyone"),
                        ],
                        default="anyone",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "smoking_policy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inside", "Inside allowed"),
                            ("outside_only", "Outside only"),
                            ("not_allowed", "Not allowed"),
                        ],
                        default="outside_only",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "guest_policy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("allowed", "Allowed"),
                            ("overnight_allowed", "Overnight allowed"),
                            ("restricted", "Restricted"),
                        ],
                        default="allowed",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(blank=True, default="23:00", null=True),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, default="07:00", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255, null=True)),
                ("rooms", models.IntegerField()),
                ("area", models.FloatField()),
                ("floor", models.IntegerField(blank=True, null=True)),
                (
                    "price_per_month",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="apartments_images")),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "apartment_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="available",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("bathrooms", models.IntegerField(default=1)),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complex",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="bookings.residentialcomplex",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="bookings.apartment",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartment_favourited",
                        to="bookings.apartment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_favourites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "apartment")},
            },
        ),
    ]
