# Generated by Django 5.0.1 on 2025-04-27 15:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="amenities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Удобства квартиры (например: WiFi, Parking)",
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="gender_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_preference", "No preference"),
                    ("male", "Male only"),
                    ("female", "Female only"),
                ],
                default="no_preference",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="guest_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("allowed", "Allowed"),
                    ("overnight_allowed", "Overnight allowed"),
                    ("restricted", "Restricted"),
                ],
                default="allowed",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="max_age",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="min_age",
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="musical_instruments",
            field=models.CharField(
                blank=True,
                choices=[
                    ("allowed", "Allowed"),
                    ("negotiable", "Negotiable"),
                    ("not_allowed", "Not Allowed"),
                ],
                default="negotiable",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="pets_allowed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="smoking_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inside", "Inside allowed"),
                    ("outside_only", "Outside only"),
                    ("not_allowed", "Not allowed"),
                ],
                default="outside_only",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="tenant_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("students_only", "Students only"),
                    ("working_professionals", "Working professionals"),
                    ("anyone", "Anyone"),
                ],
                default="anyone",
                max_length=50,
                null=True,
            ),
        ),
    ]
