# Generated by Django 5.0.1 on 2025-04-29 23:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_complaint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="complaint",
            unique_together={("user", "apartment")},
        ),
    ]
