# Generated by Django 5.0.1 on 2025-05-06 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0008_review_image_review_rating_alter_feedback_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("student", "Student"), ("landlord", "Landlord")],
                        max_length=10,
                    ),
                ),
                (
                    "type_of_booking",
                    models.CharField(
                        choices=[("single", "Один"), ("shared", "С подселением")],
                        max_length=10,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.apartment",
                    ),
                ),
            ],
        ),
    ]
