# Generated by Django 5.0.1 on 2025-05-06 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0009_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="is_top",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TopPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                (
                    "apartment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_promotion",
                        to="bookings.apartment",
                    ),
                ),
            ],
        ),
    ]
