# Generated by Django 5.0.1 on 2025-05-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0010_apartment_is_top_toppromotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        choices=[(3, "3 дня"), (15, "15 дней"), (30, "30 дней")]
                    ),
                ),
                ("original_price", models.PositiveIntegerField()),
                ("discounted_price", models.PositiveIntegerField()),
                ("discount_percent", models.PositiveIntegerField()),
            ],
        ),
    ]
