# Generated by Django 5.2 on 2025-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0013_notification_type_alter_notification_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(max_length=255),
        ),
    ]
