# Generated by Django 5.2 on 2025-05-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0014_alter_notification_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("favourite", "Favourite"),
                    ("booking", "Booking Request"),
                    ("review", "Review"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
