# Generated by Django 5.2 on 2025-05-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0015_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="residentialcomplex",
            name="technical_specifications",
            field=models.TextField(blank=True, null=True),
        ),
    ]
