# Generated by Django 5.2 on 2025-05-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0016_residentialcomplex_technical_specifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="residentialcomplex",
            name="apartment_features",
            field=models.TextField(blank=True, null=True),
        ),
    ]
