# Generated by Django 5.2 on 2025-05-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0017_residentialcomplex_apartment_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="decision",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                ],
                default="new",
                max_length=10,
            ),
        ),
    ]
