# Generated by Django 5.2 on 2025-05-08 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0019_bookingdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="complaint",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="complaint",
            name="residential_complex",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.residentialcomplex",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.apartment",
            ),
        ),
        migrations.AddConstraint(
            model_name="complaint",
            constraint=models.UniqueConstraint(
                fields=("user", "apartment"), name="unique_user_apartment_complaint"
            ),
        ),
        migrations.AddConstraint(
            model_name="complaint",
            constraint=models.UniqueConstraint(
                fields=("user", "residential_complex"), name="unique_user_rc_complaint"
            ),
        ),
    ]
