# Generated by Django 5.0.1 on 2025-06-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0020_alter_complaint_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="region",
            field=models.CharField(
                choices=[
                    ("almaly", "Алмалинский"),
                    ("auyezov", "Ауэзовский"),
                    ("bostandyk", "Бостандыкский"),
                    ("medeu", "Медеуский"),
                    ("nauryzbay", "Наурызбайский"),
                    ("turksib", "Турксибский"),
                    ("zhetysu", "Жетысуский"),
                    ("alatau", "Алатауский"),
                ],
                default="almaly",
                max_length=50,
                null=True,
            ),
        ),
    ]
