# Generated by Django 5.0.1 on 2025-06-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0021_apartment_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="rental_type",
            field=models.CharField(
                choices=[("day", "Short-term"), ("month", "Long-term")],
                default="month",
                max_length=10,
            ),
        ),
    ]
