# Generated by Django 5.1.6 on 2025-03-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="price_per_day",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
