# Generated by Django 5.0.1 on 2025-05-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0007_feedback_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="users_images/"),
        ),
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedback",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="users_images/"),
        ),
    ]
