# Generated by Django 5.0.1 on 2025-04-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0013_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
