# Generated by Django 5.1.6 on 2025-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_is_verified_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="users_images"),
        ),
    ]
