# Generated by Django 5.0.1 on 2025-03-17 10:08

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="code",
            field=models.CharField(
                default=users.models.generate_verification_code,
                max_length=4,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="expiration",
            field=models.DateTimeField(default=users.models.generate_expiration_time),
        ),
    ]
