# Generated by Django 5.0.1 on 2025-03-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0013_review"),
        ("users", "0006_alter_emailverification_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="favourites",
            field=models.ManyToManyField(
                blank=True, related_name="favourited_by", to="bookings.apartment"
            ),
        ),
    ]
