# Generated by Django 5.0.1 on 2025-03-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="experience",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
