# Generated by Django 5.0.1 on 2025-03-20 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_residentialcomplex_remove_apartment_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="address",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="city",
        ),
        migrations.AddField(
            model_name="apartment",
            name="complex",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="bookings.residentialcomplex",
            ),
        ),
    ]
