# Generated by Django 5.0.1 on 2025-03-20 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_remove_apartment_address_remove_apartment_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="complex",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="bookings.residentialcomplex",
            ),
        ),
    ]
