# Generated by Django 5.0.1 on 2025-03-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0005_alter_apartment_complex"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="apartment_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
