# Generated by Django 5.0.1 on 2025-03-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0006_apartment_apartment_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="residentialcomplex",
            name="image",
            field=models.ImageField(null=True, upload_to="apartments_images"),
        ),
    ]
