# Generated by Django 5.0.1 on 2025-03-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0007_residentialcomplex_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="bathrooms",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="apartment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("booked", "Booked"),
                    ("unavailable", "Unavailable"),
                ],
                default="available",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="residentialcomplex",
            name="amenities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="residentialcomplex",
            name="parking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="residentialcomplex",
            name="total_floors",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
