# Generated by Django 5.0.1 on 2025-03-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0009_alter_apartment_price_per_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="price_per_month",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
