# Generated by Django 5.0.1 on 2025-03-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0011_residentialcomplex_gender_preference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residentialcomplex",
            name="gender_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_preference", "No preference"),
                    ("male", "Male only"),
                    ("female", "Female only"),
                ],
                default="no_preference",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="residentialcomplex",
            name="guest_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("allowed", "Allowed"),
                    ("overnight_allowed", "Overnight allowed"),
                    ("restricted", "Restricted"),
                ],
                default="allowed",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="residentialcomplex",
            name="max_age",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name="residentialcomplex",
            name="min_age",
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AlterField(
            model_name="residentialcomplex",
            name="musical_instruments",
            field=models.CharField(
                blank=True,
                choices=[
                    ("allowed", "Allowed"),
                    ("negotiable", "Negotiable"),
                    ("not_allowed", "Not Allowed"),
                ],
                default="negotiable",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="residentialcomplex",
            name="pets_allowed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="residentialcomplex",
            name="quiet_hours_end",
            field=models.TimeField(blank=True, default="07:00", null=True),
        ),
        migrations.AlterField(
            model_name="residentialcomplex",
            name="quiet_hours_start",
            field=models.TimeField(blank=True, default="23:00", null=True),
        ),
        migrations.AlterField(
            model_name="residentialcomplex",
            name="smoking_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inside", "Inside allowed"),
                    ("outside_only", "Outside only"),
                    ("not_allowed", "Not allowed"),
                ],
                default="outside_only",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="residentialcomplex",
            name="tenant_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("students_only", "Students only"),
                    ("working_professionals", "Working professionals"),
                    ("anyone", "Anyone"),
                ],
                default="anyone",
                max_length=50,
                null=True,
            ),
        ),
    ]
