# Generated by Django 5.0.1 on 2025-06-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_card_photo",
            field=models.ImageField(blank=True, null=True, upload_to="id_cards/"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_student_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified_landlord",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="ownership_doc",
            field=models.FileField(blank=True, null=True, upload_to="ownership_docs/"),
        ),
        migrations.AddField(
            model_name="user",
            name="student_id_photo",
            field=models.ImageField(blank=True, null=True, upload_to="student_ids/"),
        ),
    ]
